### 作業
目前已經學過許多的模型，相信大家對整體流程應該比較掌握了，這次作業請改用**手寫辨識資料集**，步驟流程都是一樣的，請試著自己撰寫程式碼來完成所有步驟

In [33]:
from sklearn import datasets, metrics
from sklearn.model_selection import train_test_split
import numpy as np
digits = datasets.load_digits()
print(digits.data.shape)
print(digits.data[0,:])

(1797, 64)
[ 0.  0.  5. 13.  9.  1.  0.  0.  0.  0. 13. 15. 10. 15.  5.  0.  0.  3.
 15.  2.  0. 11.  8.  0.  0.  4. 12.  0.  0.  8.  8.  0.  0.  5.  8.  0.
  0.  9.  8.  0.  0.  4. 11.  0.  1. 12.  7.  0.  0.  2. 14.  5. 10. 12.
  0.  0.  0.  0.  6. 13. 10.  0.  0.  0.]


In [25]:
from sklearn.ensemble import GradientBoostingClassifier
x_train, x_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.2, random_state=4)

In [17]:
clf = GradientBoostingClassifier(loss="deviance", learning_rate=0.1, n_estimators=20)
clf.fit(x_train, y_train)
y_pred = clf.predict(x_test)
acu = metrics.accuracy_score(y_test, y_pred)
matrix = metrics.confusion_matrix(y_test, y_pred)
print('accuracy of GD = {}'.format(acu))
print(matrix)

accuracy of GD = 0.9416666666666667
[[38  0  0  0  0  0  0  0  0  0]
 [ 1 29  1  1  0  0  0  0  0  0]
 [ 1  0 38  1  0  0  0  0  1  0]
 [ 0  0  0 28  0  1  1  0  2  1]
 [ 1  0  0  0 36  0  0  0  0  0]
 [ 0  0  0  0  0 36  0  0  0  2]
 [ 0  0  0  0  1  0 32  0  2  0]
 [ 0  0  0  0  1  0  0 37  0  0]
 [ 0  1  0  0  0  0  0  0 32  0]
 [ 1  0  0  0  0  0  0  1  0 33]]


In [36]:
print(np.max(digits.data))
print(np.min(digits.data))
data = digits.data / np.max(digits.data)
x_train, x_test, y_train, y_test = train_test_split(data, digits.target, test_size=0.2, random_state=4)

16.0
0.0


In [37]:
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression(penalty='l2', solver='lbfgs', multi_class='multinomial', max_iter=1000)
clf.fit(x_train, y_train)
y_pred = clf.predict(x_test)
acu = metrics.accuracy_score(y_test, y_pred)
matrix = metrics.confusion_matrix(y_test, y_pred)
print('accuracy of Logistic R= {}'.format(acu))
print(matrix)

accuracy of Logistic R= 0.9861111111111112
[[38  0  0  0  0  0  0  0  0  0]
 [ 0 31  1  0  0  0  0  0  0  0]
 [ 0  0 41  0  0  0  0  0  0  0]
 [ 0  0  0 32  0  1  0  0  0  0]
 [ 0  0  0  0 37  0  0  0  0  0]
 [ 0  0  0  0  0 38  0  0  0  0]
 [ 0  0  0  0  0  0 34  0  1  0]
 [ 0  0  0  0  0  0  0 38  0  0]
 [ 0  2  0  0  0  0  0  0 31  0]
 [ 0  0  0  0  0  0  0  0  0 35]]


In [38]:
#Logistic Regression表現意外的好= =